import puppeteer from "puppeteer";

function getBadgeColor(level) {
  const colors = {
    High: "#ef4444",
    Medium: "#f59e0b",
    Low: "#22c55e",
  };
  return colors[level] || "#6b7280";
}

function generateHTML(packData) {
  const risksHTML = packData.risks
    .map(
      (risk) => `
      <div class="risk-item">
        <div class="risk-header">
          <span class="risk-title">${risk.title}</span>
          <span class="badge" style="background: ${getBadgeColor(risk.confidence)}">${risk.confidence}</span>
        </div>
        <p class="risk-desc">${risk.description}</p>
      </div>
    `
    )
    .join("");

  const docsHTML = packData.missingDocuments
    .map(
      (doc) => `
      <tr>
        <td>${doc.name}</td>
        <td><span class="badge" style="background: ${doc.required ? "#ef4444" : "#6b7280"}">${doc.required ? "Required" : "Optional"}</span></td>
        <td>${doc.category}</td>
      </tr>
    `
    )
    .join("");

  const actionsHTML = packData.actionItems
    .map(
      (action) => `
      <tr>
        <td>${action.title}</td>
        <td><span class="badge" style="background: ${getBadgeColor(action.priority)}">${action.priority}</span></td>
        <td>${action.assignee}</td>
        <td>${action.dueDays} days</td>
      </tr>
    `
    )
    .join("");

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', system-ui, sans-serif;
      color: #1e293b;
      line-height: 1.6;
    }
    .header {
      background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
      color: white;
      padding: 40px;
      text-align: center;
    }
    .header h1 {
      font-size: 28px;
      font-weight: 700;
      margin-bottom: 8px;
    }
    .header p {
      color: #94a3b8;
      font-size: 14px;
    }
    .content {
      padding: 30px 40px;
    }
    .section {
      margin-bottom: 30px;
    }
    .section-title {
      font-size: 18px;
      font-weight: 700;
      color: #0f172a;
      margin-bottom: 15px;
      padding-bottom: 8px;
      border-bottom: 2px solid #e2e8f0;
    }
    .summary-box {
      background: #f8fafc;
      border-left: 4px solid #00d4ff;
      padding: 20px;
      border-radius: 0 8px 8px 0;
      font-style: italic;
      color: #475569;
    }
    .risk-item {
      background: white;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 15px;
      margin-bottom: 12px;
    }
    .risk-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 8px;
    }
    .risk-title {
      font-weight: 600;
      font-size: 15px;
    }
    .risk-desc {
      color: #64748b;
      font-size: 13px;
    }
    .badge {
      color: white;
      padding: 4px 12px;
      border-radius: 20px;
      font-size: 11px;
      font-weight: 600;
      text-transform: uppercase;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 13px;
    }
    th {
      background: #f1f5f9;
      padding: 12px;
      text-align: left;
      font-weight: 600;
      color: #475569;
      border-bottom: 2px solid #e2e8f0;
    }
    td {
      padding: 12px;
      border-bottom: 1px solid #e2e8f0;
    }
    tr:hover {
      background: #f8fafc;
    }
    .footer {
      text-align: center;
      padding: 20px;
      color: #94a3b8;
      font-size: 11px;
      border-top: 1px solid #e2e8f0;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>AI Inspection Pack Report</h1>
    <p>Generated by AI Inspection Pack Generator</p>
  </div>

  <div class="content">
    <div class="section">
      <div class="section-title">Summary</div>
      <div class="summary-box">${packData.summary}</div>
    </div>

    <div class="section">
      <div class="section-title">Risks Identified (${packData.risks.length})</div>
      ${risksHTML}
    </div>

    <div class="section">
      <div class="section-title">Missing Documents (${packData.missingDocuments.length})</div>
      <table>
        <thead>
          <tr><th>Document</th><th>Status</th><th>Category</th></tr>
        </thead>
        <tbody>${docsHTML}</tbody>
      </table>
    </div>

    <div class="section">
      <div class="section-title">Action Items (${packData.actionItems.length})</div>
      <table>
        <thead>
          <tr><th>Action</th><th>Priority</th><th>Assignee</th><th>Due</th></tr>
        </thead>
        <tbody>${actionsHTML}</tbody>
      </table>
    </div>
  </div>

  <div class="footer">
    AI Inspection Pack Generator &bull; Confidential Report
  </div>
</body>
</html>
  `;
}

export async function generatePDF(packData) {
  const browser = await puppeteer.launch({ headless: "new" });
  try {
    const page = await browser.newPage();
    const html = generateHTML(packData);
    await page.setContent(html, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
    });

    return pdfBuffer;
  } finally {
    await browser.close();
  }
}
